// <auto-generated />
using System;
using AbacProjectBackend.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AbacProjectBackend.Migrations
{
    [DbContext(typeof(PlanetDbContext))]
    [Migration("20231114164703_explorers-team")]
    partial class explorersteam
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AbacProjectBackend.Models.Explorer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Explorers");
                });

            modelBuilder.Entity("AbacProjectBackend.Models.Planet", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImagePath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Planets");
                });

            modelBuilder.Entity("AbacProjectBackend.Models.PlanetExplorer", b =>
                {
                    b.Property<Guid>("PlanetId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ExplorerId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("PlanetId", "ExplorerId");

                    b.HasIndex("ExplorerId");

                    b.ToTable("PlanetExplorers");
                });

            modelBuilder.Entity("AbacProjectBackend.Models.PlanetExplorer", b =>
                {
                    b.HasOne("AbacProjectBackend.Models.Explorer", "Explorer")
                        .WithMany("PlanetExplorers")
                        .HasForeignKey("ExplorerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AbacProjectBackend.Models.Planet", "Planet")
                        .WithMany("PlanetExplorers")
                        .HasForeignKey("PlanetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Explorer");

                    b.Navigation("Planet");
                });

            modelBuilder.Entity("AbacProjectBackend.Models.Explorer", b =>
                {
                    b.Navigation("PlanetExplorers");
                });

            modelBuilder.Entity("AbacProjectBackend.Models.Planet", b =>
                {
                    b.Navigation("PlanetExplorers");
                });
#pragma warning restore 612, 618
        }
    }
}
